# <span style="color:darkblue"> Lecture 3 Exercises </span>



## Short Questions

<font size = "5">

1. What is a codebook?
2. How you define a missing value in Python?
2. What is chaining?

In [2]:
# Write your answers here as comments

# 1.    A codebook is a tool which generates a descriptive summary of a dataset's structure, variables, and data types.
# 2.    A missing value in Python can be defined with numpy.NaN which stands for Not a Number.
# 3.    Chaining is a way of calling multiple methods on a single object in a continuous line.

## Long Questions

<font size = "5">

Import the libraries "numpy" and "pandas"

In [3]:
# Write your own code

import numpy as np
import pandas as pd

<font size = "5">

(a) Replace values from intervals

<font size = "3">

- Import the dataset "data_raw/students.csv" to a new object "students"
- Use "pd.cut()" to assign the column "numericgrade" to a letter grade <br>
using the following table

<img src="figures/grading_scale.png" alt="drawing" width="600"/>

In [4]:
# Write your own code

students = pd.read_csv('data_raw/students.csv')

bins_grades = [-1, 54, 59, 64, 69, 74, 79, 82, 86, 92, 100]
labels_grades = ['F', 'D', 'C-', 'C', 'C+', 'B-', 'B', 'B+', 'A-', 'A']

students["lettergrade"] = pd.cut(students["numericgrade"],
                                  bins = bins_grades,
                                  labels = labels_grades,
                                  right = True)

students

    studentid  numericgrade lettergrade
0           1            61          C-
1           2             0           F
2           3            14           F
3           4            57           D
4           5            72          C+
5           6            93           A
6           7            40           F
7           8            11           F
8           9             3           F
9          10            63          C-
10         11             7           F
11         12            46           F
12         13            75          B-
13         14            95           A
14         15            22           F
15         16            40           F
16         17            53           F
17         18            57           D
18         19            82           B
19         20            50           F
20         21             8           F
21         22            87          A-
22         23            82           B
23         24            30           F
24         25            62          C-

<font size = "5">

For questions (b)-(e) use "results.csv", <br>
a dataset on competitive car racing

Import the dataset "data/raw_results.csv" to <br>
 a new object "results"

<font size = "5">

(b) Check column types

<font size = "3">

- View the dataset
- Use the function "results.dtypes" to get the column types
- Search for the "results" table in "codebook/f1_codebook.pdf".
- Does the type of the "milliseconds" column agree with the codebook? <br>
i.e. is it an integer, float, or string/object?


HINT: See Lectures 13 and 14 for how to interpret the codebook

In [5]:
# Write your own code

results = pd.read_csv('data_raw/results.csv')
results.dtypes

# The type of milliseconds in the codebook is an integer
# The type of milliseconds from dtypes is str
# The types do not agree

resultId             int64
raceId               int64
driverId             int64
constructorId        int64
number                 str
grid                 int64
position               str
positionText           str
positionOrder        int64
points             float64
laps                 int64
time                   str
milliseconds           str
fastestLap             str
rank                   str
fastestLapTime         str
fastestLapSpeed        str
statusId             int64
dtype: object

<font size = "5">

(c) Clean a column

<font size = "3">

- Import the dataset "data_raw/results.csv" to a new object "results"
- Our goal is to replace any string values in the column "milliseconds" <br>
to missing values (NaNs) and covert to numeric
- To do so, go to Lecture 13 and follow the setups under the headings
    - "Extract list of non-numeric values"
    - "Replace certain values"
    - "Convert column to numeric"

HINT: substitute "milliseconds" instead of "alt", <br>
and the dataset "results" instead of "circuits"

In [6]:
# Write your own code

results = pd.read_csv('data_raw/results.csv')

# From 'Extract list of non-numeric values'

subset = results.query('milliseconds.str.isnumeric() == False')
list_unique = pd.unique(subset["milliseconds"])
print(list_unique)

# This command replaces the values of the "milliseconds" column
results["milliseconds"] = results["milliseconds"].replace('\\N', np.nan)

# pd.to_numeric() converts a column to numeric
# Before you use this option, make sure to "clean" the variable
# as we did before by checking what the non-numeric values are

results["milliseconds"] = pd.to_numeric(results["milliseconds"])

<ArrowStringArray>
['\N']
Length: 1, dtype: str

<font size = "5">

(d) Groupby + Aggregate

<font size = "3">

- Compute the mean and standard deviation of "laps", <br>
grouping by "constructorId". Store the new dataset <br>
as "results_agg"
- Sort the aggregate dataset in decending <br>
order of mean laps using ".sort_values()"

HINT: See Lecture 14 <br>

In [7]:
# Write your own code

results_agg = results.groupby('constructorId')['laps'].agg(['mean', 'std'])

results_agg = results_agg.sort_values('mean', ascending=False)

results_agg

                     mean        std
constructorId
149            198.500000   2.121320
112            197.000000   4.242641
109            184.285714  32.912583
119            178.666667  36.950417
108            163.764706  63.148168
...                   ...        ...
93               0.000000        NaN
61               0.000000   0.000000
137              0.000000        NaN
91               0.000000        NaN
74               0.000000   0.000000

[210 rows x 2 columns]

<font size = "5" >

(e) Query + Groupby + Aggregate

<font size = "3">

- Use ".query()" to subset observations with <br>
'race_id >= 200'
- Compute the mean and standard deviation of "laps", <br>
grouping by "constructorId". Store the new dataset <br>
as "results_agg"

Hint: See Lecture 11 (to refresh ".query()") and <br>
Lecture 14 for how to combine it with ".groupby()"

In [8]:
# Write your own code

race_id_query = results.query('raceId >= 200')

results_agg = race_id_query.groupby('constructorId')['laps'].agg(['mean', 'std'])

results_agg

                    mean        std
constructorId
1              50.093510  23.147774
3              51.349621  21.064902
4              46.396450  22.565290
5              51.787879  18.281774
6              50.305798  25.953854
...                  ...        ...
209            52.282051  19.522147
210            51.434028  19.915741
211            54.684211  17.680279
213            52.393443  19.883361
214            54.204545  17.951505

[201 rows x 2 columns]


<font size = "5">

(f) Replace the values of a column

<font size = "3">

- Import the "data_raw/constructor_standings.csv" file
- Replace the values "E" with 11 in the column "positionText"
- Create a new column "positionNumeric" that converts <br>
the modified "positionText" column from string to numeric <br>
using ```pd.to_numeric()```

In [9]:
# Write your own code

constructor_standings = pd.read_csv('data_raw/constructor_standings.csv')

constructor_standings['positionText'] = constructor_standings['positionText'].replace('E', 11)

constructor_standings['positionNumeric'] = pd.to_numeric(
    constructor_standings['positionText']
)

constructor_standings

,constructorStandingsId,raceId,constructorId,points,position,positionText,wins,positionNumeric
0,1,18,1,14.0,1,1,1,1
1,2,18,2,8.0,3,3,0,3
2,3,18,3,9.0,2,2,0,2
3,4,18,4,5.0,4,4,0,4
4,5,18,5,2.0,5,5,0,5
...,...,...,...,...,...,...,...,...
12936,28408,1098,210,0.0,6,6,0,6
12937,28409,1098,1,0.0,7,7,0,7
12938,28410,1098,131,0.0,8,8,0,8
12939,28411,1098,9,0.0,9,9,0,9
12940,28412,1098,3,0.0,10,10,0,10

<font size = "5">

(g) Recode a numeric colum

<font size = "3">

- Import the "data_raw/races.csv" file
- Recode the "year" column into a new column "year_brackets" <br>
with the following categories

$\qquad$ ``` ["1950-1970","1971-1990","1991-2005", "2006-2020", "2020-onwards"] ```

$\qquad$ HINT: Use the "pd.cut()" command.

In [10]:
# Write your own code

races = pd.read_csv('data_raw/races.csv')

bins_years = [1950, 1970, 1990, 2005, 2020, float('inf')]
labels_years = ['1950-1970', '1971-1990', '1991-2005', '2006-2020', '2020-onwards']

races['year_brackets'] = pd.cut(
    races['year'],
    bins=bins_years,
    labels=labels_years,
    right=True
)

races

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time,year_brackets
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,2006-2020
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,2006-2020
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,2006-2020
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,2006-2020
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,2006-2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1097,1116,2023,19,69,United States Grand Prix,2023-10-22,19:00:00,https://en.wikipedia.org/wiki/2023_United_Stat...,2023-10-20,17:30:00,2023-10-21,18:00:00,\N,\N,2023-10-20,21:00:00,2023-10-21,22:00:00,2020-onwards
1098,1117,2023,20,32,Mexico City Grand Prix,2023-10-29,20:00:00,https://en.wikipedia.org/wiki/2023_Mexico_City...,2023-10-27,18:30:00,2023-10-27,22:00:00,2023-10-28,17:30:00,2023-10-28,21:00:00,\N,\N,2020-onwards
1099,1118,2023,21,18,São Paulo Grand Prix,2023-11-05,17:00:00,https://en.wikipedia.org/wiki/2023_S%C3%A3o_Pa...,2023-11-03,14:30:00,2023-11-04,14:30:00,\N,\N,2023-11-03,18:00:00,2023-11-04,18:30:00,2020-onwards
1100,1119,2023,22,80,Las Vegas Grand Prix,2023-11-19,06:00:00,https://en.wikipedia.org/wiki/2023_Las_Vegas_G...,2023-11-17,04:30:00,2023-11-17,08:00:00,2023-11-18,04:30:00,2023-11-18,08:00:00,\N,\N,2020-onwards
1101,1120,2023,23,24,Abu Dhabi Grand Prix,2023-11-26,13:00:00,https://en.wikipedia.org/wiki/2023_Abu_Dhabi_G...,2023-11-24,09:30:00,2023-11-24,13:00:00,2023-11-25,10:30:00,2023-11-25,14:00:00,\N,\N,2020-onwards

<font size = "5">

(h) Aggregate and query

<font size = "3">

- Import the "data_raw/constructor_standings.csv" file
- Subset the observations for 'raceId == 10' using ```.query()```
- Obtain the sum of "points" by "constructorId" <br> 
(the team) using ``` .groupby().agg() ```
- Subset the teams with a sum of points $\ge 50$
- Store the results of all these operations in a dataframe <br>
```constructor_standings_agg ```

In [11]:
# Write your own code

constructor_standings = pd.read_csv('data_raw/constructor_standings.csv')

constructor_standings_agg = (
    constructor_standings.query("raceId == 10")
    .groupby('constructorId')
    .agg(sum_points = ('points', 'sum'))
    .query("sum_points > 50")
)

constructor_standings_agg

               sum_points
constructorId
9                    98.5
23                  114.0

<font size = "5">

(i) Aggregate and sort

<font size = "3">

- Import the "data_raw/constructor_standings.csv" file
- Obtain the sum of "points" by "constructorId" <br> 
(the team) using ``` .groupby().agg() ```
- Sort the teams in descending order using of <br>
the sum of points using ``` .sort_values() ```

In [12]:
# Write your own code

constructor_standings = pd.read_csv('data_raw/constructor_standings.csv')

constructor_standings_agg = (
    constructor_standings
    .groupby('constructorId')
    .agg(sum_points = ('points', 'sum'))
    .sort_values('sum_points', ascending=False)
)

constructor_standings_agg

               sum_points
constructorId
6                 90204.0
131               71808.5
9                 64986.5
1                 57188.5
3                 32093.5
...                   ...
93                    0.0
92                    0.0
90                    0.0
89                    0.0
91                    0.0

[159 rows x 1 columns]

<font size = "5">

(j) Rename column

<font size = "3">

- Import the "data_raw/constructor_standings.csv" file
- Rename the column "wins" to "wins_constructor"

HINT: Create a dictionary and use ```.rename(columns = ...)``` <br>

In [13]:
# Write your own code

constructor_standings = pd.read_csv('data_raw/constructor_standings.csv')

new_names = {"wins" : "wins_constructor"}

constructor_standings.rename(columns=new_names)

,constructorStandingsId,raceId,constructorId,points,position,positionText,wins_constructor
0,1,18,1,14.0,1,1,1
1,2,18,2,8.0,3,3,0
2,3,18,3,9.0,2,2,0
3,4,18,4,5.0,4,4,0
4,5,18,5,2.0,5,5,0
...,...,...,...,...,...,...,...
12936,28408,1098,210,0.0,6,6,0
12937,28409,1098,1,0.0,7,7,0
12938,28410,1098,131,0.0,8,8,0
12939,28411,1098,9,0.0,9,9,0
12940,28412,1098,3,0.0,10,10,0

<font size = "5">

(k) Merge dataset

<font size = "3">

- Import the "data_raw/constructor_standings.csv" and <br>
"data_raw/constructors.csv" files
- Create a new dataset with  ```pd.merge()``` using <br>
"constructor_standings" as the primary dataset, and <br>
"constructors" as the secondary dataset, merging on <br>
the column "constructorId"
- To get full points **ONLY** merge the "nationality" column <br>
from the secondary dataset (not all the columns)

HINT: Use ```[[...]]``` to extract a subset of columns <br>
from the secondary dataset before merging, including the <br>
"constructorId" column

In [14]:
# Write your own code

constructor_standings = pd.read_csv('data_raw/constructor_standings.csv')
constructors = pd.read_csv('data_raw/constructors.csv')

constructors_merge = pd.merge(constructor_standings,
                       constructors[['constructorId', 'nationality']],
                       on = "constructorId",
                       how = "left")

constructors_merge

,constructorStandingsId,raceId,constructorId,points,position,positionText,wins,nationality
0,1,18,1,14.0,1,1,1,British
1,2,18,2,8.0,3,3,0,German
2,3,18,3,9.0,2,2,0,British
3,4,18,4,5.0,4,4,0,French
4,5,18,5,2.0,5,5,0,Italian
...,...,...,...,...,...,...,...,...
12936,28408,1098,210,0.0,6,6,0,American
12937,28409,1098,1,0.0,7,7,0,British
12938,28410,1098,131,0.0,8,8,0,German
12939,28411,1098,9,0.0,9,9,0,Austrian
12940,28412,1098,3,0.0,10,10,0,British

<font size = "5">

(l) Formatted results table

<font size = "3">

-  For the dataset you computed above construct a \
descriptive statistics table
- Round the numbers and change the column names to something \
more interpretable

In [34]:
# Write your own code

constructors_merge = constructor_standings.merge(
    constructors[['constructorId', 'name', 'nationality']],
    on='constructorId'
)

constructors_merge[['name', 'nationality', 'points', 'position', 'wins']].rename(columns={
    'name': 'Manufacturer',
    'nationality': 'Nationality',
    'points': 'Total Championship Points',
    'position': 'Championship Position',
    'wins': 'Race Wins'
}).style.format({
    'Points' : '{:,.1f}'
}).set_caption("Manufacturer Performance Summary").hide(axis="index")

#QUESTION - is this the type of descriptive statistics expected or should it be like below?

manufacturer_stats = (
    constructors_merge
    .groupby("name")
    .agg(
        total_points=("points", "sum"),
        average_position=("position", "mean"),
        total_wins=("wins", "sum")
    )
    .sort_values("total_points", ascending=False)
    .reset_index()
)

manufacturer_stats


manufacturer_stats.rename(columns={
    "name": "Manufacturer",
    "total_points": "Total Points",
    "average_position": "Average Position",
    "total_wins": "Total Wins"
}).style.format({
    "Total Points": "{:,.0f}",
    "Average Position": "{:,.1f}",
    "Total Wins": "{:,.0f}"
}).set_caption("Manufacturer Performance Summary").hide(axis="index")